### ISSUE TITLE
ajax-form ignores empty fields

### ISSUE THREAD

**Issue by eximius313** [rnicholus/ajax-form#59]
I have a simple form containing two input fields.
When one of them is empty, ajax-form doesn't mention it in the request.
I think, that ajax-form should put its name with empty value instead of ignoring it, because this has serious implications with validation.

**Comment by rnicholus** [comment]
The intent was to submit form data via XHR following the same rules as a native form submit. It looks like this particular details was missed. I'll fix in the next release.

Currently, I am (very slowly due to other commitments) working on #55. Once that is complete, I'll be sure to work on this before releasing ajax-form 2.0.

**Comment by rnicholus** [comment]
This is fixed in the 2.0.0 branch, to be released with v2.
