### ISSUE TITLE
Polymer 1.0 now requires webcomponents-lite, that change breaks firefox compatibility

### ISSUE THREAD

**Issue by mafiuss** [rnicholus/ajax-form#69]
According with https://www.polymer-project.org/1.0/docs/migration.html#polyfill, instead of webcomponents.js we should use webcomponents-lite.js, when I do that change in the demo.html in ajax-form and try to load it in firefox I got:

TypeError: this.createShadowRoot is not a function
root = this.createShadowRoot();
(ajax-form.js) line 471, col 31

that would be here: https://github.com/rnicholus/ajax-form/blob/master/ajax-form.js#L471

**Comment by rnicholus** [comment]
This is due to the fact that ajax-form currently relies on shadow dom. The lite polyfill doesn't cover shadow dom, so you'll need to use the any polyfill that includes support for shadow dom in any browser that doesn't natively implement it.

I may be able to remove the shadow dom dependency, making ajax-form a simple custom element. I'll have to give that some more thought though. In the meantime you'll have to ensure shadow dom is supported in whatever browser you are using, either natively or via a polyfill.

**Comment by rnicholus** [comment]
Going to look into removing Shadow DOM dependence from ajax-form now...

**Comment by rnicholus** [comment]
This change is now live as of 2.1.0. You may safely use the webcomponents-lite.js polyfill.
