### ISSUE TITLE
Make available via bower

### ISSUE THREAD

**Issue by lukasoppermann** [rnicholus/ajax-form#87]
Hey,

I am not writing a node app, so I actually get all my components via bower. Can you please make this package available via bower, so I can easily get it? Thanks.

**Comment by rnicholus** [comment]
You don't need to write a node app to use npm. Simply install node, and `npm install ajax-form`.

**Comment by lukasoppermann** [comment]
I know that, it might have been badly put. I do not use npm, only bower. I do not really want to use npm just for this one component.

**Comment by rnicholus** [comment]
I disagree about the "front-end" focused aspect of bower. Both are just JS/CSS package managers. But I can understand and appreciate that some prefer one over the other. That said, I won't have time in the near future to dedicate to ajax-form due to a number of other current side projects. But I'd be happy to accept a pull request that allows this to be published to bower. I'm pretty sure ajax-form is already registered w/ bower, so all that may be needed is a proper `bower.json` file.

**Comment by lukasoppermann** [comment]
I will send a PR.
